# Generated by Django 2.2 on 2020-01-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ipAddress', models.TextField(max_length=255)),
                ('macAddress', models.TextField(max_length=255)),
                ('manufacturer', models.TextField(max_length=255)),
                ('model', models.TextField(max_length=255)),
                ('assetType', models.TextField(max_length=255)),
                ('operatingSystem', models.TextField(max_length=255)),
                ('firmwareVersion', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('isFirmwareScanned', models.BooleanField()),
                ('discontinued', models.BooleanField()),
                ('outdated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('ipCount', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssetImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.TextField(blank=True, null=True)),
                ('importtype', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
