# Generated by Django 2.2 on 2020-01-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='discontinued',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='outdated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
