# Generated by Django 2.2 on 2020-01-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='lastestfirmwareversion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
