# Generated by Django 2.2 on 2020-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_lastestfirmwareversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetimport',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
