# Generated by Django 2.2 on 2020-01-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_asset_vulnerabilites_vulnerabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilities',
            name='cvss',
            field=models.TextField(),
        ),
    ]
