# Generated by Django 2.2 on 2020-01-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_auto_20200118_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_FirmwareDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetid', models.IntegerField()),
                ('fdetailid', models.IntegerField()),
                ('scanid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FirmwareComponentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetid', models.IntegerField()),
                ('firmwarename', models.TextField()),
                ('firmwarehash', models.TextField()),
                ('checksum', models.TextField()),
                ('componentname', models.TextField()),
                ('version', models.TextField()),
                ('vulnerabilities', models.TextField()),
                ('issues', models.TextField()),
            ],
        ),
    ]
