# Generated by Django 2.2 on 2020-01-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_scan_ovid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilities',
            name='assetid',
        ),
    ]
