# Generated by Django 2.2 on 2020-01-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_remove_vulnerabilities_assetid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmwarecomponentdetail',
            name='assetid',
        ),
    ]
