# Generated by Django 2.2 on 2020-01-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_remove_firmwarecomponentdetail_assetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_vulnerabilites',
            name='assetid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
    ]
