# Generated by Django 2.2 on 2020-01-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0009_auto_20200120_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_vulnerabilites',
            name='assetid',
            field=models.IntegerField(),
        ),
    ]
