# Generated by Django 2.2 on 2020-01-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0013_auto_20200120_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_firmwaredetail',
            name='assetid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='asset_firmwaredetail',
            name='fdetailid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.FirmwareComponentDetail'),
        ),
        migrations.AlterField(
            model_name='asset_ov_vulnerabilites',
            name='assetid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='asset_ov_vulnerabilites',
            name='ovid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.OV_Vulnerabilities'),
        ),
        migrations.AlterField(
            model_name='asset_vulnerabilites',
            name='vulid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Vulnerabilities'),
        ),
    ]
