# Generated by Django 2.2 on 2020-01-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0014_auto_20200120_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ov_vulnerabilities',
            name='severity',
            field=models.IntegerField(),
        ),
    ]
