# Generated by Django 2.2 on 2020-01-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0015_auto_20200120_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ov_vulnerabilities',
            name='severity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='cvss',
            field=models.FloatField(),
        ),
    ]
