# Generated by Django 2.2 on 2020-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0017_auto_20200123_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_firmwaredetail',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset_ov_vulnerabilites',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset_vulnerabilites',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmwarecomponentdetail',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ov_vulnerabilities',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerabilities',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
